/* ApplicationWIndow.c generated by valac 0.34.1, the Vala compiler
 * generated from ApplicationWIndow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define BOILERPLATE_TYPE_APPLICATION_WINDOW (boilerplate_application_window_get_type ())
#define BOILERPLATE_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOILERPLATE_TYPE_APPLICATION_WINDOW, BoilerplateApplicationWindow))
#define BOILERPLATE_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOILERPLATE_TYPE_APPLICATION_WINDOW, BoilerplateApplicationWindowClass))
#define BOILERPLATE_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOILERPLATE_TYPE_APPLICATION_WINDOW))
#define BOILERPLATE_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOILERPLATE_TYPE_APPLICATION_WINDOW))
#define BOILERPLATE_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOILERPLATE_TYPE_APPLICATION_WINDOW, BoilerplateApplicationWindowClass))

typedef struct _BoilerplateApplicationWindow BoilerplateApplicationWindow;
typedef struct _BoilerplateApplicationWindowClass BoilerplateApplicationWindowClass;
typedef struct _BoilerplateApplicationWindowPrivate BoilerplateApplicationWindowPrivate;

struct _BoilerplateApplicationWindow {
	GtkApplicationWindow parent_instance;
	BoilerplateApplicationWindowPrivate * priv;
};

struct _BoilerplateApplicationWindowClass {
	GtkApplicationWindowClass parent_class;
};


static gpointer boilerplate_application_window_parent_class = NULL;

GType boilerplate_application_window_get_type (void) G_GNUC_CONST;
enum  {
	BOILERPLATE_APPLICATION_WINDOW_DUMMY_PROPERTY
};
BoilerplateApplicationWindow* boilerplate_application_window_new (GtkApplication* app);
BoilerplateApplicationWindow* boilerplate_application_window_construct (GType object_type, GtkApplication* app);


BoilerplateApplicationWindow* boilerplate_application_window_construct (GType object_type, GtkApplication* app) {
	BoilerplateApplicationWindow * self = NULL;
	GtkApplication* _tmp0_ = NULL;
	g_return_val_if_fail (app != NULL, NULL);
	_tmp0_ = app;
	self = (BoilerplateApplicationWindow*) g_object_new (object_type, "application", _tmp0_, NULL);
	return self;
}


BoilerplateApplicationWindow* boilerplate_application_window_new (GtkApplication* app) {
	return boilerplate_application_window_construct (BOILERPLATE_TYPE_APPLICATION_WINDOW, app);
}


static void boilerplate_application_window_class_init (BoilerplateApplicationWindowClass * klass) {
	boilerplate_application_window_parent_class = g_type_class_peek_parent (klass);
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/de/hannenz/boilerplate/interface/boilerplate_window.ui");
}


static void boilerplate_application_window_instance_init (BoilerplateApplicationWindow * self) {
	gtk_widget_init_template (GTK_WIDGET (self));
}


GType boilerplate_application_window_get_type (void) {
	static volatile gsize boilerplate_application_window_type_id__volatile = 0;
	if (g_once_init_enter (&boilerplate_application_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoilerplateApplicationWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) boilerplate_application_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BoilerplateApplicationWindow), 0, (GInstanceInitFunc) boilerplate_application_window_instance_init, NULL };
		GType boilerplate_application_window_type_id;
		boilerplate_application_window_type_id = g_type_register_static (gtk_application_window_get_type (), "BoilerplateApplicationWindow", &g_define_type_info, 0);
		g_once_init_leave (&boilerplate_application_window_type_id__volatile, boilerplate_application_window_type_id);
	}
	return boilerplate_application_window_type_id__volatile;
}



