/* Boilerplate.c generated by valac 0.34.1, the Vala compiler
 * generated from Boilerplate.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <locale.h>


#define BOILERPLATE_TYPE_BOILERPLATE (boilerplate_boilerplate_get_type ())
#define BOILERPLATE_BOILERPLATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOILERPLATE_TYPE_BOILERPLATE, BoilerplateBoilerplate))
#define BOILERPLATE_BOILERPLATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOILERPLATE_TYPE_BOILERPLATE, BoilerplateBoilerplateClass))
#define BOILERPLATE_IS_BOILERPLATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOILERPLATE_TYPE_BOILERPLATE))
#define BOILERPLATE_IS_BOILERPLATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOILERPLATE_TYPE_BOILERPLATE))
#define BOILERPLATE_BOILERPLATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOILERPLATE_TYPE_BOILERPLATE, BoilerplateBoilerplateClass))

typedef struct _BoilerplateBoilerplate BoilerplateBoilerplate;
typedef struct _BoilerplateBoilerplateClass BoilerplateBoilerplateClass;
typedef struct _BoilerplateBoilerplatePrivate BoilerplateBoilerplatePrivate;

#define BOILERPLATE_TYPE_APPLICATION_WINDOW (boilerplate_application_window_get_type ())
#define BOILERPLATE_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOILERPLATE_TYPE_APPLICATION_WINDOW, BoilerplateApplicationWindow))
#define BOILERPLATE_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOILERPLATE_TYPE_APPLICATION_WINDOW, BoilerplateApplicationWindowClass))
#define BOILERPLATE_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOILERPLATE_TYPE_APPLICATION_WINDOW))
#define BOILERPLATE_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOILERPLATE_TYPE_APPLICATION_WINDOW))
#define BOILERPLATE_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOILERPLATE_TYPE_APPLICATION_WINDOW, BoilerplateApplicationWindowClass))

typedef struct _BoilerplateApplicationWindow BoilerplateApplicationWindow;
typedef struct _BoilerplateApplicationWindowClass BoilerplateApplicationWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _BoilerplateBoilerplate {
	GtkApplication parent_instance;
	BoilerplateBoilerplatePrivate * priv;
};

struct _BoilerplateBoilerplateClass {
	GtkApplicationClass parent_class;
};

struct _BoilerplateBoilerplatePrivate {
	BoilerplateApplicationWindow* window;
	GSettings* settings;
};


static gpointer boilerplate_boilerplate_parent_class = NULL;

#define BOILERPLATE_app_id "de.hannenz.boilerplate"
GType boilerplate_boilerplate_get_type (void) G_GNUC_CONST;
GType boilerplate_application_window_get_type (void) G_GNUC_CONST;
#define BOILERPLATE_BOILERPLATE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BOILERPLATE_TYPE_BOILERPLATE, BoilerplateBoilerplatePrivate))
enum  {
	BOILERPLATE_BOILERPLATE_DUMMY_PROPERTY
};
BoilerplateBoilerplate* boilerplate_boilerplate_new (void);
BoilerplateBoilerplate* boilerplate_boilerplate_construct (GType object_type);
#define CONSTANTS_GETTEXT_PACKAGE "boilerplate"
#define CONSTANTS_DATADIR "/usr/local/share"
static void boilerplate_boilerplate_add_actions (BoilerplateBoilerplate* self);
static void __lambda4_ (BoilerplateBoilerplate* self);
static void ___lambda4__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void boilerplate_boilerplate_real_activate (GApplication* base);
BoilerplateApplicationWindow* boilerplate_application_window_new (GtkApplication* app);
BoilerplateApplicationWindow* boilerplate_application_window_construct (GType object_type, GtkApplication* app);
static void boilerplate_boilerplate_finalize (GObject* obj);
gint boilerplate_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


BoilerplateBoilerplate* boilerplate_boilerplate_construct (GType object_type) {
	BoilerplateBoilerplate * self = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self = (BoilerplateBoilerplate*) g_object_new (object_type, "application-id", BOILERPLATE_app_id, "flags", G_APPLICATION_FLAGS_NONE, NULL);
	_tmp0_ = g_build_filename (CONSTANTS_DATADIR, "locale", NULL);
	_tmp1_ = _tmp0_;
	bindtextdomain (CONSTANTS_GETTEXT_PACKAGE, _tmp1_);
	_g_free0 (_tmp1_);
	setlocale (LC_ALL, "");
	textdomain (CONSTANTS_GETTEXT_PACKAGE);
	bind_textdomain_codeset (CONSTANTS_GETTEXT_PACKAGE, "utf-8");
	boilerplate_boilerplate_add_actions (self);
	return self;
}


BoilerplateBoilerplate* boilerplate_boilerplate_new (void) {
	return boilerplate_boilerplate_construct (BOILERPLATE_TYPE_BOILERPLATE);
}


static void __lambda4_ (BoilerplateBoilerplate* self) {
	g_debug ("Boilerplate.vala:47: Quit action has been activated");
	gtk_main_quit ();
}


static void ___lambda4__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda4_ ((BoilerplateBoilerplate*) self);
}


static void boilerplate_boilerplate_add_actions (BoilerplateBoilerplate* self) {
	GSimpleAction* action = NULL;
	GSimpleAction* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_simple_action_new ("quit-action", NULL);
	action = _tmp0_;
	_tmp1_ = g_strdup ("<Control>q");
	_tmp2_ = g_new0 (gchar*, 1 + 1);
	_tmp2_[0] = _tmp1_;
	_tmp3_ = _tmp2_;
	_tmp3__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.quit-action", _tmp3_);
	_tmp3_ = (_vala_array_free (_tmp3_, _tmp3__length1, (GDestroyNotify) g_free), NULL);
	g_signal_connect_object (action, "activate", (GCallback) ___lambda4__g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) action);
	_g_object_unref0 (action);
}


static void boilerplate_boilerplate_real_activate (GApplication* base) {
	BoilerplateBoilerplate * self;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GSettings* _tmp2_ = NULL;
	BoilerplateApplicationWindow* _tmp3_ = NULL;
	BoilerplateApplicationWindow* _tmp4_ = NULL;
	BoilerplateApplicationWindow* _tmp5_ = NULL;
	GSettings* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	self = (BoilerplateBoilerplate*) base;
	_tmp0_ = g_application_get_application_id ((GApplication*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_settings_new (_tmp1_);
	_g_object_unref0 (self->priv->settings);
	self->priv->settings = _tmp2_;
	_tmp3_ = boilerplate_application_window_new ((GtkApplication*) self);
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->window);
	self->priv->window = _tmp3_;
	_tmp4_ = self->priv->window;
	gtk_widget_show_all ((GtkWidget*) _tmp4_);
	_tmp5_ = self->priv->window;
	gtk_window_present ((GtkWindow*) _tmp5_);
	g_debug ("Boilerplate.vala:60: %s", BOILERPLATE_app_id);
	_tmp6_ = self->priv->settings;
	_tmp7_ = g_settings_get_string (_tmp6_, "foo");
	_tmp8_ = _tmp7_;
	g_debug ("Boilerplate.vala:61: %s", _tmp8_);
	_g_free0 (_tmp8_);
	_tmp9_ = _ ("Hello, world");
	g_debug ("Boilerplate.vala:62: %s", _tmp9_);
}


static void boilerplate_boilerplate_class_init (BoilerplateBoilerplateClass * klass) {
	boilerplate_boilerplate_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (BoilerplateBoilerplatePrivate));
	((GApplicationClass *) klass)->activate = boilerplate_boilerplate_real_activate;
	G_OBJECT_CLASS (klass)->finalize = boilerplate_boilerplate_finalize;
}


static void boilerplate_boilerplate_instance_init (BoilerplateBoilerplate * self) {
	self->priv = BOILERPLATE_BOILERPLATE_GET_PRIVATE (self);
}


static void boilerplate_boilerplate_finalize (GObject* obj) {
	BoilerplateBoilerplate * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOILERPLATE_TYPE_BOILERPLATE, BoilerplateBoilerplate);
	_g_object_unref0 (self->priv->window);
	_g_object_unref0 (self->priv->settings);
	G_OBJECT_CLASS (boilerplate_boilerplate_parent_class)->finalize (obj);
}


GType boilerplate_boilerplate_get_type (void) {
	static volatile gsize boilerplate_boilerplate_type_id__volatile = 0;
	if (g_once_init_enter (&boilerplate_boilerplate_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoilerplateBoilerplateClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) boilerplate_boilerplate_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BoilerplateBoilerplate), 0, (GInstanceInitFunc) boilerplate_boilerplate_instance_init, NULL };
		GType boilerplate_boilerplate_type_id;
		boilerplate_boilerplate_type_id = g_type_register_static (gtk_application_get_type (), "BoilerplateBoilerplate", &g_define_type_info, 0);
		g_once_init_leave (&boilerplate_boilerplate_type_id__volatile, boilerplate_boilerplate_type_id);
	}
	return boilerplate_boilerplate_type_id__volatile;
}


gint boilerplate_main (gchar** args, int args_length1) {
	gint result = 0;
	BoilerplateBoilerplate* app = NULL;
	BoilerplateBoilerplate* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	_tmp0_ = boilerplate_boilerplate_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = _tmp2_;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return boilerplate_main (argv, argc);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



