/* Config.c generated by valac 0.34.1, the Vala compiler
 * generated from Config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define CONSTANTS_DATADIR "/usr/local/share"
#define CONSTANTS_PKGDATADIR "/usr/local/share/boilerplate"
#define CONSTANTS_GETTEXT_PACKAGE "boilerplate"
#define CONSTANTS_RELEASE_NAME "boilerplate"
#define CONSTANTS_VERSION "1.0.0"



