/* Overlay.c generated by valac 0.34.4, the Vala compiler
 * generated from Overlay.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define BOILERPLATE_TYPE_OVERLAY (boilerplate_overlay_get_type ())
#define BOILERPLATE_OVERLAY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOILERPLATE_TYPE_OVERLAY, BoilerplateOverlay))
#define BOILERPLATE_OVERLAY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOILERPLATE_TYPE_OVERLAY, BoilerplateOverlayClass))
#define BOILERPLATE_IS_OVERLAY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOILERPLATE_TYPE_OVERLAY))
#define BOILERPLATE_IS_OVERLAY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOILERPLATE_TYPE_OVERLAY))
#define BOILERPLATE_OVERLAY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOILERPLATE_TYPE_OVERLAY, BoilerplateOverlayClass))

typedef struct _BoilerplateOverlay BoilerplateOverlay;
typedef struct _BoilerplateOverlayClass BoilerplateOverlayClass;
typedef struct _BoilerplateOverlayPrivate BoilerplateOverlayPrivate;

struct _BoilerplateOverlay {
	GtkWindow parent_instance;
	BoilerplateOverlayPrivate * priv;
};

struct _BoilerplateOverlayClass {
	GtkWindowClass parent_class;
};


static gpointer boilerplate_overlay_parent_class = NULL;

GType boilerplate_overlay_get_type (void) G_GNUC_CONST;
enum  {
	BOILERPLATE_OVERLAY_DUMMY_PROPERTY
};
BoilerplateOverlay* boilerplate_overlay_new (void);
BoilerplateOverlay* boilerplate_overlay_construct (GType object_type);


BoilerplateOverlay* boilerplate_overlay_construct (GType object_type) {
	BoilerplateOverlay * self = NULL;
	self = (BoilerplateOverlay*) g_object_new (object_type, NULL);
	g_debug ("Overlay.vala:10: Overlay Constructor");
	return self;
}


BoilerplateOverlay* boilerplate_overlay_new (void) {
	return boilerplate_overlay_construct (BOILERPLATE_TYPE_OVERLAY);
}


static void boilerplate_overlay_class_init (BoilerplateOverlayClass * klass) {
	boilerplate_overlay_parent_class = g_type_class_peek_parent (klass);
}


static void boilerplate_overlay_instance_init (BoilerplateOverlay * self) {
}


GType boilerplate_overlay_get_type (void) {
	static volatile gsize boilerplate_overlay_type_id__volatile = 0;
	if (g_once_init_enter (&boilerplate_overlay_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoilerplateOverlayClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) boilerplate_overlay_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BoilerplateOverlay), 0, (GInstanceInitFunc) boilerplate_overlay_instance_init, NULL };
		GType boilerplate_overlay_type_id;
		boilerplate_overlay_type_id = g_type_register_static (gtk_window_get_type (), "BoilerplateOverlay", &g_define_type_info, 0);
		g_once_init_leave (&boilerplate_overlay_type_id__volatile, boilerplate_overlay_type_id);
	}
	return boilerplate_overlay_type_id__volatile;
}



